### ISSUE TITLE
Can't open beaker console after ts-gen

### ISSUE THREAD

**Issue by AtticusDavid** [osmosis-labs/beaker#115]
after type `beaker console --network testnet`, 

the following errors show up in terminal.
```bash
counter git:(main) ✗ beaker console --network testnet
beaker[testnet] ◇ /Users/agrajak/.npm/_npx/b773047406ff4129/node_modules/beaker-console/dist/index.js:315
        throw Error(msg);
              ^

Error: "CounterContract" not found in sdk.
    at errorIfNotFound (/Users/agrajak/.npm/_npx/b773047406ff4129/node_modules/beaker-console/dist/index.js:315:15)
    at /Users/agrajak/.npm/_npx/b773047406ff4129/node_modules/beaker-console/dist/index.js:269:27
    at /Users/agrajak/.npm/_npx/b773047406ff4129/node_modules/beaker-console/dist/index.js:180:16
    at Array.map (<anonymous>)
    at mapKV (/Users/agrajak/.npm/_npx/b773047406ff4129/node_modules/beaker-console/dist/index.js:178:49)
    at getContracts (/Users/agrajak/.npm/_npx/b773047406ff4129/node_modules/beaker-console/dist/index.js:265:12)
    at initializeContext (/Users/agrajak/.npm/_npx/b773047406ff4129/node_modules/beaker-console/src/console.js:82:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async run (/Users/agrajak/.npm/_npx/b773047406ff4129/node_modules/beaker-console/src/console.js:93:3)

Node.js v19.2.0
Error: Failed to execute npx
```

### Steps to reproduce
- beaker new counter ( and select `counter-example)
- beaker wasm deploy counter --signer-account test3 --no-wasm-opt --raw '{ "count": 0 }' --network testnet
- beaker wasm ts-gen counter
- beaker console --network testnet

### Enviroments
- node v19.2.0
- apple m1 air (apple silicon)
- beaker 0.1.1

**Comment by iboss-ptk** [comment]
could you try beaker 0.1.2?

**Comment by AtticusDavid** [comment]
this also doesn't work in 0.1.2 too.
I guess `Counter(target contract name in PascalCase)` is in `sdk.contracts.contracts`, not `sdk.contracts`

**Comment by iboss-ptk** [comment]
can you try changing `ts/sdk/index.ts` from

```ts
export * as contracts from "./contracts";
```

to

```ts
export * from "./contracts";
```

`ts-codegen` integration is a bit messy at the moment, need to revisit on the design.

**Comment by iboss-ptk** [comment]
updated the template and it should work out of the box by now 

https://github.com/osmosis-labs/beaker/commit/c85e728b45d623a8dc05e03a8dcc310879a933ee
